import streamlit as st
import pandas as pd

from database.database import DatabaseManager
from modules.mitre_mapper import MitreMapper


# ---------------------------------------------------
# Page Configuration
# ---------------------------------------------------

st.set_page_config(
    page_title="Alerts | SentinelAI",
    page_icon="",
    layout="wide"
)


# ---------------------------------------------------
# Initialize
# ---------------------------------------------------

db = DatabaseManager()
db.create_tables()

mitre = MitreMapper()


# ---------------------------------------------------
# Title
# ---------------------------------------------------

st.title("Security Alerts")

st.write(
    "Monitor, prioritize and investigate security alerts "
    "generated by SentinelAI."
)

st.divider()


# ---------------------------------------------------
# Load Alerts
# ---------------------------------------------------

alerts = db.get_alerts()


# ---------------------------------------------------
# Alert Statistics
# ---------------------------------------------------

critical_count = sum(
    1
    for alert in alerts
    if str(alert["alert_level"]).lower() == "critical"
)

high_count = sum(
    1
    for alert in alerts
    if str(alert["alert_level"]).lower() == "high"
)

medium_count = sum(
    1
    for alert in alerts
    if str(alert["alert_level"]).lower() == "medium"
)

low_count = sum(
    1
    for alert in alerts
    if str(alert["alert_level"]).lower() == "low"
)


col1, col2, col3, col4 = st.columns(4)

col1.metric(
    "🔴 Critical",
    critical_count
)

col2.metric(
    "🟠 High",
    high_count
)

col3.metric(
    "🟡 Medium",
    medium_count
)

col4.metric(
    "🟢 Low",
    low_count
)


st.divider()


# ---------------------------------------------------
# Alert Distribution
# ---------------------------------------------------

st.subheader("Alert Distribution")

if alerts:

    alert_distribution = pd.DataFrame({

        "Threat Level": [
            "Critical",
            "High",
            "Medium",
            "Low"
        ],

        "Count": [
            critical_count,
            high_count,
            medium_count,
            low_count
        ]

    })

    alert_distribution = alert_distribution[
        alert_distribution["Count"] > 0
    ]

    if not alert_distribution.empty:

        import plotly.express as px

        fig = px.bar(
            alert_distribution,
            x="Threat Level",
            y="Count",
            title="Security Alerts by Threat Level"
        )

        st.plotly_chart(
            fig,
            use_container_width=True
        )

st.divider()


# ---------------------------------------------------
# Filters
# ---------------------------------------------------

st.subheader("Alert Filters")

filter_col1, filter_col2 = st.columns(2)


with filter_col1:

    users = sorted(
        list(
            set(
                alert["username"]
                for alert in alerts
            )
        )
    )

    user_options = ["All Employees"] + users

    selected_user = st.selectbox(
        "Employee",
        user_options
    )


with filter_col2:

    level_options = [
        "All Levels",
        "Critical",
        "High",
        "Medium",
        "Low"
    ]

    selected_level = st.selectbox(
        "Threat Level",
        level_options
    )


# ---------------------------------------------------
# Apply Filters
# ---------------------------------------------------

filtered_alerts = alerts


if selected_user != "All Employees":

    filtered_alerts = [
        alert
        for alert in filtered_alerts
        if alert["username"] == selected_user
    ]


if selected_level != "All Levels":

    filtered_alerts = [
        alert
        for alert in filtered_alerts
        if str(alert["alert_level"]).lower()
        == selected_level.lower()
    ]


# ---------------------------------------------------
# Alert Table
# ---------------------------------------------------

st.subheader("Alert Queue")

alert_table = []


for alert in filtered_alerts:

    reason = alert["reason"]

    # Determine event for MITRE mapping
    event_name = "Download File"

    if "USB" in reason:

        event_name = "USB Inserted"

    elif "database" in reason.lower():

        event_name = "Access Database"

    elif "login" in reason.lower():

        event_name = "Login"


    technique = mitre.map_event(event_name)


    level = str(
        alert["alert_level"]
    ).lower()


    if level == "critical":

        display_level = "🔴 Critical"

    elif level == "high":

        display_level = "🟠 High"

    elif level == "medium":

        display_level = "🟡 Medium"

    else:

        display_level = "🟢 Low"


    alert_table.append({

        "Employee": alert["username"],

        "Risk Score": alert["risk_score"],

        "Threat Level": display_level,

        "MITRE ID": technique.get(
            "id",
            "N/A"
        ),

        "Technique": technique.get(
            "name",
            "Unknown"
        ),

        "Reason": reason,

        "Time": alert["timestamp"]

    })


alert_df = pd.DataFrame(
    alert_table
)


if not alert_df.empty:

    st.dataframe(
        alert_df,
        hide_index=True,
        use_container_width=True
    )

else:

    st.info(
        "No alerts match the selected filters."
    )


# ---------------------------------------------------
# Alert Details
# ---------------------------------------------------

st.divider()

st.subheader("Alert Details")

if filtered_alerts:

    alert_options = [
        f'{alert["username"]} — '
        f'{alert["alert_level"]} — '
        f'Risk {alert["risk_score"]} — '
        f'{alert["timestamp"]}'
        for alert in filtered_alerts
    ]

    selected_alert_index = st.selectbox(
        "Select an alert",
        range(len(alert_options)),
        format_func=lambda i: alert_options[i]
    )

    selected_alert = filtered_alerts[
        selected_alert_index
    ]


    detail_col1, detail_col2, detail_col3 = st.columns(3)


    with detail_col1:

        st.metric(
            "Employee",
            selected_alert["username"]
        )


    with detail_col2:

        st.metric(
            "Risk Score",
            selected_alert["risk_score"]
        )


    with detail_col3:

        st.metric(
            "Threat Level",
            selected_alert["alert_level"]
        )


    st.write("**Reason**")

    st.info(
        selected_alert["reason"]
    )


    st.write("**Generated At**")

    st.write(
        selected_alert["timestamp"]
    )

else:

    st.info(
        "Select an alert to view its details."
    )


# ---------------------------------------------------
# Investigation Shortcut
# ---------------------------------------------------

st.divider()

st.subheader("Investigate Alert")

if filtered_alerts:

    st.write(
        "Open Incident Investigation to analyze "
        "the selected employee's activity, behavioral "
        "deviations, risk history and MITRE ATT&CK mapping."
    )

    if st.button("🔍 Investigate Selected Employee"):

        st.session_state["investigation_user"] = (
            selected_alert["username"]
        )

        st.success(
            f"Selected {selected_alert['username']} "
            "for investigation."
        )

        st.info(
            "Open the Incident Investigation page "
            "from the sidebar."
        )

else:

    st.info("No alert selected for investigation.")


# ---------------------------------------------------
# Close Database
# ---------------------------------------------------

db.close()